name: CodoBrawl
version: '${project.version}'
main: za.co.codonorix.codobrawl.CodoBrawl
api-version: 1.19
authors: [ logan2971 ]
commands:
  dev:
    description: Dev command
  givecrystals:
    description: Give user crystals
  cbhelp:
    description: Displays the codobrawl help menu
  removecrystals:
    description: Removes crystals from user
  setlobby:
    description: Sets the lobby of the world.